# --------------------------------------------- ghislain.bernard@gmail.com ------------------------------------------- #
all:
  hosts:
    ubuntu.qemu.lan:
# --------------------------------------------- ghislain.bernard@gmail.com ------------------------------------------- #
