# --------------------------------------------- ghislain.bernard@gmail.com ------------------------------------------- #
- gather_facts: no
  hosts: all

  tasks:
    - name: apt vim package
      ansible.builtin.apt:
        name: vim

    - name: vimrc local file
      ansible.builtin.copy:
        dest: /etc/vim/
        src: vim/vimrc.local
# --------------------------------------------- ghislain.bernard@gmail.com ------------------------------------------- #
